import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import Navbar from "@/components/ui/navbar/navbar";

// const inter = G({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={GeistSans.className + "relative flex-col flex items-center"}>
        <Navbar />
        <main className="flex flex-col gap-4 w-full max-w-5xl p-4">
          {children}
          </main>
      </body>
    </html>
  );
}
